# Generated by Django 6.0 on 2026-01-04 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_alter_client_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CALL', 'Call'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('VISIT', 'Visit'), ('NOTE', 'Note')], default='NOTE', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='clients.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
