# Generated by Django 6.0 on 2026-01-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='type',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='user',
        ),
        migrations.AddField(
            model_name='interaction',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('call', 'Call'), ('meet', 'Meet'), ('instagram', 'Instagram'), ('web', 'Web'), ('other', 'Other')], default='whatsapp', max_length=20),
        ),
        migrations.AddField(
            model_name='interaction',
            name='direction',
            field=models.CharField(choices=[('out', 'Outgoing'), ('in', 'Incoming')], default='out', max_length=10),
        ),
        migrations.AddField(
            model_name='interaction',
            name='next_action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=120),
            preserve_default=False,
        ),
    ]
